resource "datadog_dashboard" "tfer--dashboard_4gn-3c2-zkz" {
  description  = "Generated by Terraform - testing now"
  is_read_only = "false"
  layout_type  = "ordered"
  reflow_type  = "fixed"
  title        = "Minecraft Server Dashboard[Terraform Managed]"
  url          = "/dashboard/4gn-3c2-zkz/minecraft-server-dashboard"

  widget {
    group_definition {
      background_color = "gray"
      layout_type      = "ordered"
      show_title       = "true"
      title            = "Test/Experimental"

      widget {
        timeseries_definition {
          legend_columns = ["avg", "max", "min", "sum", "value"]
          legend_layout  = "auto"

          request {
            display_type = "area"

            formula {
              formula_expression = "query1"
            }

            on_right_yaxis = "false"

            query {
              metric_query {
                data_source = "metrics"
                name        = "query1"
                query       = "avg:test2.minecraft.online.user{host:vm-37ccf7ab-68,service:minecraft,!usr.name:*_players*} by {usr.name}.as_count().rollup(avg)"
              }
            }

            style {
              line_type  = "solid"
              line_width = "normal"
              palette    = "dog_classic"
            }
          }

          show_legend = "false"
          title       = "Count Metrics Test for New Online User"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "3"
          is_column_break = "false"
          width           = "5"
          x               = "5"
          y               = "0"
        }
      }

      widget {
        timeseries_definition {
          legend_columns = ["avg", "max", "min", "sum", "value"]
          legend_layout  = "auto"

          request {
            display_type = "area"

            formula {
              formula_expression = "query1"
            }

            on_right_yaxis = "false"

            query {
              metric_query {
                data_source = "metrics"
                name        = "query1"
                query       = "sum:test.minecraft.online.user{host:vm-37ccf7ab-68,service:minecraft,!usr.name:*_players*} by {usr.name}"
              }
            }

            style {
              line_type  = "solid"
              line_width = "normal"
              palette    = "dog_classic"
            }
          }

          show_legend = "false"
          title       = "Gauge Metrics Test for New Online User"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "3"
          is_column_break = "false"
          width           = "5"
          x               = "0"
          y               = "0"
        }
      }

      widget {
        toplist_definition {
          live_span = "5m"

          request {
            formula {
              formula_expression = "query1"

              limit {
                count = "5"
                order = "desc"
              }
            }

            query {
              metric_query {
                aggregator  = "avg"
                data_source = "metrics"
                name        = "query1"
                query       = "min:test2.minecraft.online.user{host:vm-37ccf7ab-68,service:minecraft,!usr.name:*_players*} by {usr.name}.as_count()"
              }
            }
          }

          title       = "Count Metrics Test for New Online User"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "3"
          is_column_break = "false"
          width           = "5"
          x               = "5"
          y               = "3"
        }
      }

      widget {
        toplist_definition {
          live_span = "5m"

          request {
            formula {
              formula_expression = "query1"

              limit {
                count = "5"
                order = "desc"
              }
            }

            query {
              metric_query {
                aggregator  = "avg"
                data_source = "metrics"
                name        = "query1"
                query       = "sum:test.minecraft.online.user{host:vm-37ccf7ab-68, service:minecraft,host:vm-37ccf7ab-68 , !usr.name:*_players*} by {usr.name}"
              }
            }
          }

          title       = "Gauge Metrics Test for New Online User"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "3"
          is_column_break = "false"
          width           = "5"
          x               = "0"
          y               = "3"
        }
      }
    }

    widget_layout {
      height          = "7"
      is_column_break = "false"
      width           = "12"
      x               = "0"
      y               = "11"
    }
  }

  widget {
    group_definition {
      background_color = "vivid_green"
      layout_type      = "ordered"
      show_title       = "true"
      title            = "Who's online?"

      widget {
        query_value_definition {
          autoscale = "true"
          live_span = "5m"
          precision = "2"

          request {
            conditional_formats {
              comparator = "="
              hide_value = "true"
              image_url  = "https://p-qkfgo2.t2.n0.cdn.getcloudapp.com/items/rRuz45Pj/2e4f1e38-4aba-4c48-89ac-95233e9808d8.jpg?v=c16030b34a4efe76aec472bb3ed84dfd"
              palette    = "custom_image"
              value      = "0"
            }

            conditional_formats {
              comparator = ">="
              hide_value = "true"
              image_url  = "https://p-qkfgo2.t2.n0.cdn.getcloudapp.com/items/04uvly1q/8dc12861-5f2d-42fe-b900-55c2cf6449ef.jpg?v=32cc75980c55de08892a7db29e25d0f3"
              palette    = "custom_image"
              value      = "1"
            }

            formula {
              formula_expression = "default_zero(query1)"
            }

            query {
              metric_query {
                aggregator  = "avg"
                data_source = "metrics"
                name        = "query1"
                query       = "avg:minecraft.online.count{usr.name:ken_ohno}"
              }
            }
          }

          title       = "Ken"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "1"
          is_column_break = "false"
          width           = "1"
          x               = "0"
          y               = "1"
        }
      }

      widget {
        query_value_definition {
          autoscale = "true"
          live_span = "5m"
          precision = "2"

          request {
            conditional_formats {
              comparator = "="
              hide_value = "true"
              image_url  = "https://p-qkfgo2.t2.n0.cdn.getcloudapp.com/items/rRuz45Pj/2e4f1e38-4aba-4c48-89ac-95233e9808d8.jpg?v=c16030b34a4efe76aec472bb3ed84dfd"
              palette    = "custom_image"
              value      = "0"
            }

            conditional_formats {
              comparator = ">="
              hide_value = "true"
              image_url  = "https://p-qkfgo2.t2.n0.cdn.getcloudapp.com/items/04uvly1q/8dc12861-5f2d-42fe-b900-55c2cf6449ef.jpg?v=32cc75980c55de08892a7db29e25d0f3"
              palette    = "custom_image"
              value      = "1"
            }

            formula {
              formula_expression = "default_zero(query1)"
            }

            query {
              metric_query {
                aggregator  = "avg"
                data_source = "metrics"
                name        = "query1"
                query       = "avg:minecraft.online.count{usr.name:kyouheiohno}"
              }
            }
          }

          title       = "Kyouhei"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "1"
          is_column_break = "false"
          width           = "1"
          x               = "1"
          y               = "1"
        }
      }

      widget {
        query_value_definition {
          autoscale = "true"
          live_span = "5m"
          precision = "2"

          request {
            conditional_formats {
              comparator = "="
              hide_value = "true"
              image_url  = "https://p-qkfgo2.t2.n0.cdn.getcloudapp.com/items/rRuz45Pj/2e4f1e38-4aba-4c48-89ac-95233e9808d8.jpg?v=c16030b34a4efe76aec472bb3ed84dfd"
              palette    = "custom_image"
              value      = "0"
            }

            conditional_formats {
              comparator = ">="
              hide_value = "true"
              image_url  = "https://p-qkfgo2.t2.n0.cdn.getcloudapp.com/items/04uvly1q/8dc12861-5f2d-42fe-b900-55c2cf6449ef.jpg?v=32cc75980c55de08892a7db29e25d0f3"
              palette    = "custom_image"
              value      = "1"
            }

            formula {
              formula_expression = "default_zero(query1)"
            }

            query {
              metric_query {
                aggregator  = "avg"
                data_source = "metrics"
                name        = "query1"
                query       = "avg:minecraft.online.count{usr.name:mamomamoru}"
              }
            }
          }

          title       = "Mamoru"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "1"
          is_column_break = "false"
          width           = "1"
          x               = "0"
          y               = "0"
        }
      }

      widget {
        query_value_definition {
          autoscale = "true"
          live_span = "5m"
          precision = "2"

          request {
            conditional_formats {
              comparator = "="
              hide_value = "true"
              image_url  = "https://p-qkfgo2.t2.n0.cdn.getcloudapp.com/items/rRuz45Pj/2e4f1e38-4aba-4c48-89ac-95233e9808d8.jpg?v=c16030b34a4efe76aec472bb3ed84dfd"
              palette    = "custom_image"
              value      = "0"
            }

            conditional_formats {
              comparator = ">="
              hide_value = "true"
              image_url  = "https://p-qkfgo2.t2.n0.cdn.getcloudapp.com/items/04uvly1q/8dc12861-5f2d-42fe-b900-55c2cf6449ef.jpg?v=32cc75980c55de08892a7db29e25d0f3"
              palette    = "custom_image"
              value      = "1"
            }

            formula {
              formula_expression = "default_zero(query1)"
            }

            query {
              metric_query {
                aggregator  = "avg"
                data_source = "metrics"
                name        = "query1"
                query       = "avg:minecraft.online.count{usr.name:yuohno}"
              }
            }
          }

          title       = "Yu"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "1"
          is_column_break = "false"
          width           = "1"
          x               = "1"
          y               = "0"
        }
      }

      widget {
        toplist_definition {
          live_span = "5m"

          request {
            conditional_formats {
              comparator      = ">"
              custom_bg_color = "#000000"
              hide_value      = "false"
              palette         = "custom_bg"
              value           = "0"
            }

            formula {
              formula_expression = "exclude_null(query1)"

              limit {
                count = "1"
                order = "desc"
              }
            }

            query {
              metric_query {
                aggregator  = "avg"
                data_source = "metrics"
                name        = "query1"
                query       = "avg:minecraft.online.count{*} by {usr.name}"
              }
            }
          }

          title       = "Online User"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "2"
          is_column_break = "false"
          width           = "4"
          x               = "2"
          y               = "0"
        }
      }
    }

    widget_layout {
      height          = "3"
      is_column_break = "false"
      width           = "7"
      x               = "0"
      y               = "0"
    }
  }

  widget {
    group_definition {
      background_color = "vivid_orange"
      layout_type      = "ordered"
      show_title       = "true"
      title            = "Server Performance"

      widget {
        manage_status_definition {
          color_preference    = "background"
          display_format      = "counts"
          hide_zero_counts    = "true"
          query               = "Minecraft Server Process"
          show_last_triggered = "false"
          show_priority       = "false"
          sort                = "status,asc"
          summary_type        = "monitors"
        }

        widget_layout {
          height          = "2"
          is_column_break = "false"
          width           = "2"
          x               = "0"
          y               = "0"
        }
      }

      widget {
        query_value_definition {
          autoscale = "true"
          live_span = "1d"
          precision = "2"

          request {
            conditional_formats {
              comparator = "="
              hide_value = "true"
              image_url  = "https://p-qkfgo2.t2.n0.cdn.getcloudapp.com/items/rRuz45Pj/2e4f1e38-4aba-4c48-89ac-95233e9808d8.jpg?v=c16030b34a4efe76aec472bb3ed84dfd"
              palette    = "white_on_green"
              value      = "0"
            }

            conditional_formats {
              comparator = ">="
              hide_value = "false"
              palette    = "white_on_red"
              value      = "1"
            }

            formula {
              formula_expression = "default_zero(query1)"
            }

            query {
              event_query {
                compute {
                  aggregation = "count"
                  interval    = "0"
                }

                data_source = "logs"
                indexes     = ["*"]
                name        = "query1"

                search {
                  query = "service:minecraft \"Considering it to be crashed, server will forcibly shutdown.\""
                }

                storage = "hot"
              }
            }
          }

          title       = "Server Force Shutdown"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "1"
          is_column_break = "false"
          width           = "2"
          x               = "0"
          y               = "2"
        }
      }

      widget {
        sunburst_definition {
          hide_total = "true"
          live_span  = "1w"

          request {
            formula {
              formula_expression = "a"
            }

            query {
              metric_query {
                aggregator  = "sum"
                data_source = "metrics"
                name        = "a"
                query       = "sum:minecraft.user.joined{*} by {usr.name}.as_count()"
              }
            }
          }

          title       = "Minecraft Active Users Past 1 Week"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "3"
          is_column_break = "false"
          width           = "3"
          x               = "2"
          y               = "0"
        }
      }

      widget {
        timeseries_definition {
          legend_columns = ["avg", "max", "min", "sum", "value"]
          legend_layout  = "auto"

          request {
            display_type = "bars"

            formula {
              formula_expression = "a"
            }

            formula {
              formula_expression = "query1"
            }

            on_right_yaxis = "false"

            query {
              event_query {
                compute {
                  aggregation = "count"
                  interval    = "600000"
                }

                data_source = "logs"
                indexes     = ["*"]
                name        = "a"

                search {
                  query = "\"Can't keep up! Is the server overloaded?\" status:warn service:minecraft"
                }

                storage = "hot"
              }
            }

            query {
              event_query {
                compute {
                  aggregation = "count"
                  interval    = "600000"
                }

                data_source = "logs"
                indexes     = ["*"]
                name        = "query1"

                search {
                  query = "service:minecraft \"moved too quickly\" status:warn"
                }

                storage = "hot"
              }
            }

            style {
              palette = "warm"
            }
          }

          request {
            display_type = "line"

            formula {
              formula_expression = "query0"
            }

            on_right_yaxis = "true"

            query {
              event_query {
                compute {
                  aggregation = "avg"
                  interval    = "600000"
                  metric      = "@behind.ms"
                }

                data_source = "logs"
                indexes     = ["*"]
                name        = "query0"

                search {
                  query = "\"Can't keep up! Is the server overloaded?\" status:warn service:minecraft"
                }

                storage = "hot"
              }
            }

            style {
              line_type  = "solid"
              line_width = "normal"
              palette    = "cool"
            }
          }

          show_legend = "false"
          title       = "Server Overloaded Signals"
          title_align = "left"
          title_size  = "16"

          yaxis {
            include_zero = "false"
            scale        = "linear"
          }
        }

        widget_layout {
          height          = "3"
          is_column_break = "false"
          width           = "7"
          x               = "5"
          y               = "0"
        }
      }

      widget {
        timeseries_definition {
          legend_columns = ["avg", "max", "min", "sum", "value"]
          legend_layout  = "auto"

          request {
            display_type = "bars"

            formula {
              formula_expression = "a"
            }

            on_right_yaxis = "false"

            query {
              metric_query {
                data_source = "metrics"
                name        = "a"
                query       = "sum:minecraft.user.joined{*} by {usr.name}.as_count()"
              }
            }

            style {
              palette = "dog_classic"
            }
          }

          request {
            display_type = "bars"

            formula {
              formula_expression = "query0"
            }

            on_right_yaxis = "false"

            query {
              metric_query {
                data_source = "metrics"
                name        = "query0"
                query       = "sum:minecraft.user.left{*} by {usr.name}.as_count()"
              }
            }

            style {
              line_type  = "solid"
              line_width = "normal"
              palette    = "warm"
            }
          }

          request {
            display_type = "line"

            formula {
              formula_expression = "query0"
            }

            on_right_yaxis = "true"

            query {
              metric_query {
                data_source = "metrics"
                name        = "query0"
                query       = "max:minecraft.online.count{*}"
              }
            }

            style {
              line_type  = "solid"
              line_width = "normal"
              palette    = "green"
            }
          }

          right_yaxis {
            include_zero = "true"
            max          = "4"
          }

          show_legend = "false"
          title       = "Minecraft Login/Logout"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "2"
          is_column_break = "false"
          width           = "6"
          x               = "0"
          y               = "3"
        }
      }

      widget {
        timeseries_definition {
          legend_layout = "auto"

          request {
            on_right_yaxis = "false"

            query {
              metric_query {
                data_source = "metrics"
                name        = "query1"
                query       = "system.load.15{host:vm-37ccf7ab-68}"
              }
            }
          }

          request {
            on_right_yaxis = "false"

            query {
              metric_query {
                data_source = "metrics"
                name        = "query1"
                query       = "system.load.1{host:vm-37ccf7ab-68}"
              }
            }
          }

          request {
            on_right_yaxis = "false"

            query {
              metric_query {
                data_source = "metrics"
                name        = "query1"
                query       = "system.load.5{host:vm-37ccf7ab-68}"
              }
            }
          }

          show_legend = "true"
          title       = "Load Averages 1-5-15"
        }

        widget_layout {
          height          = "2"
          is_column_break = "false"
          width           = "6"
          x               = "6"
          y               = "3"
        }
      }
    }

    widget_layout {
      height          = "6"
      is_column_break = "false"
      width           = "12"
      x               = "0"
      y               = "3"
    }
  }

  widget {
    group_definition {
      background_color = "vivid_purple"
      layout_type      = "ordered"
      show_title       = "true"
      title            = "Death Count/Reason"

      widget {
        list_stream_definition {
          request {
            columns {
              field = "content"
              width = "auto"
            }

            columns {
              field = "status_line"
              width = "auto"
            }

            columns {
              field = "timestamp"
              width = "auto"
            }

            query {
              data_source  = "logs_stream"
              query_string = "service:minecraft @usr.name:Villager"

              sort {
                column = "timestamp"
                order  = "desc"
              }

              storage = "hot"
            }

            response_format = "event_list"
          }

          title       = "Villager Died Log Past 1 Day"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "4"
          is_column_break = "false"
          width           = "2"
          x               = "0"
          y               = "2"
        }
      }

      widget {
        query_table_definition {
          request {
            formula {
              alias              = "count"
              cell_display_mode  = "bar"
              formula_expression = "exclude_null(query1)"

              limit {
                count = "25"
                order = "desc"
              }
            }

            limit = "0"

            query {
              metric_query {
                aggregator  = "sum"
                data_source = "metrics"
                name        = "query1"
                query       = "sum:minecraft.user.event{minecraft.event:*,!minecraft.event:lost_connection*,!minecraft.event:*made*,!minecraft.event:*has_reached*,!minecraft.event:*has_completed*,usr.name:ken_ohno} by {minecraft.event}.as_count()"
              }
            }
          }

          title       = "Ken"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "4"
          is_column_break = "false"
          width           = "2"
          x               = "4"
          y               = "2"
        }
      }

      widget {
        query_table_definition {
          request {
            formula {
              alias              = "count"
              cell_display_mode  = "bar"
              formula_expression = "exclude_null(query1)"

              limit {
                count = "25"
                order = "desc"
              }
            }

            limit = "0"

            query {
              metric_query {
                aggregator  = "sum"
                data_source = "metrics"
                name        = "query1"
                query       = "sum:minecraft.user.event{minecraft.event:*,!minecraft.event:lost_connection*,!minecraft.event:*made*,!minecraft.event:*has_reached*,!minecraft.event:*has_completed*,usr.name:kyouheiohno} by {minecraft.event}.as_count()"
              }
            }
          }

          title       = "Kyouhei"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "4"
          is_column_break = "false"
          width           = "2"
          x               = "8"
          y               = "2"
        }
      }

      widget {
        query_table_definition {
          request {
            formula {
              alias              = "count"
              cell_display_mode  = "bar"
              formula_expression = "exclude_null(query1)"

              limit {
                count = "25"
                order = "desc"
              }
            }

            limit = "0"

            query {
              metric_query {
                aggregator  = "sum"
                data_source = "metrics"
                name        = "query1"
                query       = "sum:minecraft.user.event{minecraft.event:*,!minecraft.event:lost_connection*,!minecraft.event:*made*,!minecraft.event:*has_reached*,!minecraft.event:*has_completed*,usr.name:mamomamoru} by {minecraft.event}.as_count()"
              }
            }
          }

          title       = "Mamoru"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "4"
          is_column_break = "false"
          width           = "2"
          x               = "2"
          y               = "2"
        }
      }

      widget {
        query_table_definition {
          request {
            formula {
              alias              = "count"
              cell_display_mode  = "bar"
              formula_expression = "exclude_null(query1)"

              limit {
                count = "25"
                order = "desc"
              }
            }

            limit = "0"

            query {
              metric_query {
                aggregator  = "sum"
                data_source = "metrics"
                name        = "query1"
                query       = "sum:minecraft.user.event{minecraft.event:*,!minecraft.event:lost_connection*,!minecraft.event:*made*,!minecraft.event:*has_reached*,!minecraft.event:*has_completed*,usr.name:yuohno} by {minecraft.event}.as_count()"
              }
            }
          }

          title       = "Yu"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "4"
          is_column_break = "false"
          width           = "2"
          x               = "6"
          y               = "2"
        }
      }

      widget {
        query_value_definition {
          autoscale   = "false"
          custom_unit = "人"
          live_span   = "1d"
          precision   = "0"

          request {
            conditional_formats {
              comparator = "="
              hide_value = "false"
              palette    = "white_on_green"
              value      = "0"
            }

            conditional_formats {
              comparator = ">="
              hide_value = "false"
              palette    = "white_on_red"
              value      = "1"
            }

            formula {
              formula_expression = "default_zero(query1)"
            }

            query {
              event_query {
                compute {
                  aggregation = "count"
                  interval    = "0"
                }

                data_source = "logs"
                indexes     = ["*"]
                name        = "query1"

                search {
                  query = "service:minecraft @usr.name:Villager died"
                }

                storage = "hot"
              }
            }
          }

          timeseries_background {
            type = "area"

            yaxis {
              include_zero = "true"
            }
          }

          title       = "Minecraft Villager Died Count Past 1 Day"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "2"
          is_column_break = "false"
          width           = "2"
          x               = "0"
          y               = "0"
        }
      }

      widget {
        sunburst_definition {
          hide_total = "false"

          request {
            formula {
              alias              = "count"
              formula_expression = "exclude_null(query1)"
            }

            query {
              metric_query {
                aggregator  = "sum"
                data_source = "metrics"
                name        = "query1"
                query       = "sum:minecraft.user.event{usr.name:ken_ohno , minecraft.event:*, !minecraft.event:lost_connection* ,!minecraft.event:*made* ,!minecraft.event:*has_reached* ,!minecraft.event:*has_completed*} by {minecraft.event}.as_count()"
              }
            }
          }

          title       = "Ken"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "2"
          is_column_break = "false"
          width           = "2"
          x               = "4"
          y               = "0"
        }
      }

      widget {
        sunburst_definition {
          hide_total = "false"

          request {
            formula {
              alias              = "count"
              formula_expression = "exclude_null(query1)"
            }

            query {
              metric_query {
                aggregator  = "sum"
                data_source = "metrics"
                name        = "query1"
                query       = "sum:minecraft.user.event{usr.name:kyouheiohno , minecraft.event:*, !minecraft.event:lost_connection* ,!minecraft.event:*made* ,!minecraft.event:*has_reached* ,!minecraft.event:*has_completed*} by {minecraft.event}.as_count()"
              }
            }
          }

          title       = "Kyouhei"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "2"
          is_column_break = "false"
          width           = "2"
          x               = "8"
          y               = "0"
        }
      }

      widget {
        sunburst_definition {
          hide_total = "false"

          request {
            formula {
              alias              = "count"
              formula_expression = "exclude_null(query1)"
            }

            query {
              metric_query {
                aggregator  = "sum"
                data_source = "metrics"
                name        = "query1"
                query       = "sum:minecraft.user.event{usr.name:mamomamoru , minecraft.event:*, !minecraft.event:lost_connection* ,!minecraft.event:*made* ,!minecraft.event:*has_reached* ,!minecraft.event:*has_completed*} by {minecraft.event}.as_count()"
              }
            }
          }

          title       = "Mamoru"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "2"
          is_column_break = "false"
          width           = "2"
          x               = "2"
          y               = "0"
        }
      }

      widget {
        sunburst_definition {
          hide_total = "false"

          request {
            formula {
              alias              = "count"
              formula_expression = "exclude_null(query1)"
            }

            query {
              metric_query {
                aggregator  = "sum"
                data_source = "metrics"
                name        = "query1"
                query       = "sum:minecraft.user.event{usr.name:yuohno, minecraft.event:*, !minecraft.event:lost_connection* ,!minecraft.event:*made* ,!minecraft.event:*has_reached* ,!minecraft.event:*has_completed*} by {minecraft.event}.as_count()"
              }
            }
          }

          title       = "Yu"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "2"
          is_column_break = "false"
          width           = "2"
          x               = "6"
          y               = "0"
        }
      }
    }

    widget_layout {
      height          = "7"
      is_column_break = "false"
      width           = "12"
      x               = "0"
      y               = "9"
    }
  }

  widget {
    group_definition {
      background_color = "vivid_yellow"
      layout_type      = "ordered"
      show_title       = "true"
      title            = "System Metrics/Logs"

      widget {
        list_stream_definition {
          request {
            columns {
              field = "content"
              width = "auto"
            }

            columns {
              field = "status_line"
              width = "auto"
            }

            columns {
              field = "timestamp"
              width = "auto"
            }

            query {
              data_source  = "logs_stream"
              query_string = "service:minecraft !\"Thread RCON Client /127.0.0.1\""

              sort {
                column = "timestamp"
                order  = "desc"
              }

              storage = "hot"
            }

            response_format = "event_list"
          }

          title       = "Log Stream"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "4"
          is_column_break = "false"
          width           = "6"
          x               = "2"
          y               = "0"
        }
      }

      widget {
        query_value_definition {
          autoscale   = "true"
          custom_unit = "cores"
          precision   = "2"

          request {
            conditional_formats {
              comparator = ">"
              hide_value = "false"
              palette    = "white_on_green"
              value      = "1"
            }

            formula {
              formula_expression = "query1"
            }

            query {
              metric_query {
                aggregator  = "avg"
                data_source = "metrics"
                name        = "query1"
                query       = "avg:system.cpu.num_cores{host:vm-37ccf7ab-68}"
              }
            }
          }

          timeseries_background {
            type = "bars"
          }

          title       = "CPU"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "2"
          is_column_break = "false"
          width           = "2"
          x               = "0"
          y               = "0"
        }
      }

      widget {
        query_value_definition {
          autoscale = "true"
          precision = "2"

          request {
            conditional_formats {
              comparator = ">"
              hide_value = "false"
              palette    = "white_on_green"
              value      = "1"
            }

            formula {
              formula_expression = "query1"
            }

            query {
              metric_query {
                aggregator  = "avg"
                data_source = "metrics"
                name        = "query1"
                query       = "avg:system.mem.total{host:vm-37ccf7ab-68}"
              }
            }
          }

          timeseries_background {
            type = "bars"
          }

          title       = "Memory"
          title_align = "left"
          title_size  = "16"
        }

        widget_layout {
          height          = "2"
          is_column_break = "false"
          width           = "2"
          x               = "0"
          y               = "2"
        }
      }

      widget {
        timeseries_definition {
          legend_layout = "auto"

          marker {
            display_type = "error dashed"
            label        = "full"
            value        = "y = 100"
          }

          request {
            display_type = "line"

            formula {
              formula_expression = "query1 * 100"
            }

            on_right_yaxis = "false"

            query {
              metric_query {
                data_source = "metrics"
                name        = "query1"
                query       = "max:system.disk.in_use{host:vm-37ccf7ab-68} by {device}"
              }
            }
          }

          show_legend = "true"
          title       = "Disk usage by device (%)"
        }

        widget_layout {
          height          = "2"
          is_column_break = "false"
          width           = "4"
          x               = "0"
          y               = "8"
        }
      }

      widget {
        timeseries_definition {
          legend_layout = "auto"

          marker {
            display_type = "info solid"
            value        = "0 < y < 100"
          }

          request {
            display_type = "area"

            formula {
              formula_expression = "query1"
            }

            on_right_yaxis = "false"

            query {
              process_query {
                data_source       = "process"
                is_normalized_cpu = "true"
                limit             = "100"
                metric            = "process.stat.cpu.total_pct"
                name              = "query1"
              }
            }

            style {
              palette = "dog_classic"
            }
          }

          show_legend = "true"
          title       = "CPU Usage by Process (%)"
        }

        widget_layout {
          height          = "2"
          is_column_break = "false"
          width           = "4"
          x               = "8"
          y               = "2"
        }
      }

      widget {
        timeseries_definition {
          legend_layout = "auto"

          request {
            display_type = "area"

            formula {
              formula_expression = "query1"
            }

            formula {
              formula_expression = "query2 - query1"
            }

            on_right_yaxis = "false"

            query {
              metric_query {
                data_source = "metrics"
                name        = "query1"
                query       = "sum:system.mem.usable{host:vm-37ccf7ab-68}"
              }
            }

            query {
              metric_query {
                data_source = "metrics"
                name        = "query2"
                query       = "sum:system.mem.total{host:vm-37ccf7ab-68}"
              }
            }
          }

          show_legend = "true"
          title       = "Memory breakdown"
        }

        widget_layout {
          height          = "2"
          is_column_break = "false"
          width           = "4"
          x               = "4"
          y               = "4"
        }
      }

      widget {
        timeseries_definition {
          legend_layout = "auto"

          request {
            display_type   = "area"
            on_right_yaxis = "false"

            query {
              metric_query {
                data_source = "metrics"
                name        = "query1"
                query       = "system.cpu.idle{host:vm-37ccf7ab-68}"
              }
            }

            query {
              metric_query {
                data_source = "metrics"
                name        = "query2"
                query       = "system.cpu.system{host:vm-37ccf7ab-68}"
              }
            }

            query {
              metric_query {
                data_source = "metrics"
                name        = "query3"
                query       = "system.cpu.iowait{host:vm-37ccf7ab-68}"
              }
            }

            query {
              metric_query {
                data_source = "metrics"
                name        = "query4"
                query       = "system.cpu.user{host:vm-37ccf7ab-68}"
              }
            }

            query {
              metric_query {
                data_source = "metrics"
                name        = "query5"
                query       = "system.cpu.stolen{host:vm-37ccf7ab-68}"
              }
            }
          }

          show_legend = "true"
          title       = "CPU usage (%)"
        }

        widget_layout {
          height          = "2"
          is_column_break = "false"
          width           = "4"
          x               = "8"
          y               = "0"
        }
      }

      widget {
        timeseries_definition {
          legend_layout = "auto"

          request {
            on_right_yaxis = "false"

            query {
              metric_query {
                data_source = "metrics"
                name        = "query1"
                query       = "avg:system.swap.free{host:vm-37ccf7ab-68}"
              }
            }

            query {
              metric_query {
                data_source = "metrics"
                name        = "query2"
                query       = "avg:system.swap.used{host:vm-37ccf7ab-68}"
              }
            }
          }

          show_legend = "true"
          title       = "Available Swap"
        }

        widget_layout {
          height          = "2"
          is_column_break = "false"
          width           = "4"
          x               = "4"
          y               = "6"
        }
      }

      widget {
        timeseries_definition {
          legend_layout = "auto"

          request {
            on_right_yaxis = "false"

            query {
              metric_query {
                data_source = "metrics"
                name        = "query1"
                query       = "max:system.io.await{host:vm-37ccf7ab-68} by {device}"
              }
            }
          }

          show_legend = "true"
          title       = "Disk latency (by device)"
        }

        widget_layout {
          height          = "2"
          is_column_break = "false"
          width           = "4"
          x               = "8"
          y               = "4"
        }
      }

      widget {
        timeseries_definition {
          legend_layout = "auto"

          request {
            formula {
              formula_expression = "0 - query1"
            }

            on_right_yaxis = "false"

            query {
              metric_query {
                data_source = "metrics"
                name        = "query1"
                query       = "sum:system.net.bytes_sent{host:vm-37ccf7ab-68}"
              }
            }
          }

          request {
            on_right_yaxis = "false"

            query {
              metric_query {
                data_source = "metrics"
                name        = "query1"
                query       = "sum:system.net.bytes_rcvd{host:vm-37ccf7ab-68}"
              }
            }
          }

          show_legend = "true"
          title       = "Network traffic (bytes per sec)"
        }

        widget_layout {
          height          = "2"
          is_column_break = "false"
          width           = "4"
          x               = "8"
          y               = "6"
        }
      }

    }

    widget_layout {
      height          = "11"
      is_column_break = "true"
      width           = "12"
      x               = "0"
      y               = "0"
    }
  }

  widget {
    image_definition {
      has_background   = "false"
      has_border       = "false"
      horizontal_align = "center"
      sizing           = "contain"
      url              = "http://pngimg.com/uploads/minecraft/minecraft_PNG74.png"
      vertical_align   = "center"
    }

    widget_layout {
      height          = "2"
      is_column_break = "false"
      width           = "1"
      x               = "8"
      y               = "1"
    }
  }

  widget {
    image_definition {
      has_background   = "false"
      has_border       = "false"
      horizontal_align = "center"
      sizing           = "contain"
      url              = "https://mama-asobitai.com/wp-content/uploads/2021/10/56e2a0a4314f3553e69e33f2c81e6136.png"
      vertical_align   = "center"
    }

    widget_layout {
      height          = "2"
      is_column_break = "false"
      width           = "1"
      x               = "9"
      y               = "1"
    }
  }

  widget {
    image_definition {
      has_background   = "false"
      has_border       = "false"
      horizontal_align = "center"
      sizing           = "contain"
      url              = "https://static.wikia.nocookie.net/minecraft_ja_gamepedia/images/f/fc/Iron_Ingot_JE3_BE2.png"
      vertical_align   = "center"
    }

    widget_layout {
      height          = "2"
      is_column_break = "false"
      width           = "1"
      x               = "10"
      y               = "1"
    }
  }

  widget {
    image_definition {
      has_background   = "false"
      has_border       = "false"
      horizontal_align = "center"
      sizing           = "contain"
      url              = "https://www.minecraft.net/content/dam/games/minecraft/logos/logo-minecraft.svg"
      vertical_align   = "center"
    }

    widget_layout {
      height          = "1"
      is_column_break = "false"
      width           = "4"
      x               = "7"
      y               = "0"
    }
  }

  widget {
    image_definition {
      has_background   = "false"
      has_border       = "false"
      horizontal_align = "center"
      sizing           = "contain"
      url              = "https://www.minecraft.net/etc.clientlibs/minecraft/clientlibs/main/resources/img/minecraft-creeper-face.jpg"
      vertical_align   = "center"
    }

    widget_layout {
      height          = "2"
      is_column_break = "false"
      width           = "1"
      x               = "7"
      y               = "1"
    }
  }
}
